### ISSUE TITLE
theme.css可否手动修改配色或自动获取主题配色

### ISSUE THREAD

**Issue by AvoidantPerDis** [BryceAndJuly/Whiteboard#13]
如题，我一般用任我行主题，savor一类的颜色与默认相差很大，看起来不适应

**Comment by BryceAndJuly** [comment]
样式当然可以自定义啊，挂件里那个theme.css就是我在用的主题删减部分用不上的样式后放进去的，你完全可以换成你自己的。

如果发现有些CSS选择器对应不上，打开【开发者工具】重新调整选择器就是了——其实一般不用调整，因为预览文档的DOM结构跟笔记里是一样的。

![开发者工具](https://github.com/BryceAndJuly/Whiteboard/assets/58081876/72173140-9b7c-4121-9f3c-ca64c9050bb9)

**Comment by AvoidantPerDis** [comment]
OK，谢谢，那我能不能先把主题的css的复制进去？有哪些是原css必须保留的代码？

**Comment by BryceAndJuly** [comment]
应该没有必须保留的吧，那个theme.css里的都是自定义的样式。
基础必要的样式都放在base.css里了。

**Comment by AvoidantPerDis** [comment]
我试试

**Comment by AvoidantPerDis** [comment]
OK 可以了

**Comment by BryceAndJuly** [comment]
暂时不搞这个了，有些theme.css里还引用了其他CSS文件，到时候文件路径容易出问题。

**Comment by AvoidantPerDis** [comment]
ok

**Comment by BryceAndJuly** [comment]
emm，刚刚说的不够严谨，theme.css里有个样式还是加回去比较好，不然那个任务列表前面的框框位置可能会有偏差。

```css
/* 任务列表——待办列表——前方勾选的方框 */
.protyle-wysiwyg [data-node-id].li>.protyle-action.protyle-action--task svg {
    zoom: 1.2;
}
```
