### ISSUE TITLE
与插件【增强思源笔记】的底部反链功能冲突

### ISSUE THREAD

**Issue by HopeLHP** [BryceAndJuly/Whiteboard#23]
类似修改文档主界面的插件会产生冲突，例如插件【增强思源笔记】的底部反链功能会在文档主界面显示反链，可能就是因为挂件是铺满文档的形式呈现的。
这种倒也不是bug，就是不知道有没有好的方式兼容，或者在挂件时禁用该类插件的此类功能。
![image](https://github.com/BryceAndJuly/Whiteboard/assets/70339118/813e8f42-abc4-4647-aaf2-418c9abaeeca)

**Comment by BryceAndJuly** [comment]
那就把白板所在文档底部的反链面板隐藏掉吧。
SiYuan V3.0.17，在`设置`——`外观`——`代码片段`中，添加CSS代码片段来隐藏掉白板界面的反链面板。

```css
.protyle-top:has(+ .protyle-wysiwyg.protyle-wysiwyg--attr[alias="whiteboard"]) ~ .enhanceProtyleBottomContainer{
 display: none !important;
}
```
