### ISSUE TITLE
可以做成插件吗

### ISSUE THREAD

**Issue by TinkMingKing** [BryceAndJuly/Whiteboard#26]
感觉插件体验会更好，虽然已经有了类似的，但是做得没有这个体验好

**Comment by BryceAndJuly** [comment]
但是感觉做成插件的话，会引入以下几个问题：

1. 不好兼容移动端
2. 不好解决白板层级嵌套问题
3. 不方便通过嵌入块直接搜索和嵌入，在全局搜索中也不好搜到

第一点，目前来说，挂件的兼容性会好一点，作为思源本身支持的内容块，直接套在IFrame，在移动端没有啥大的兼容问题。

第二点，我看现有白板的插件都是一层平铺的白板文件，想必是层级嵌套的问题不好解决，我大概搞不定。挂件形式的白板虽然不是原生文档，是通过铺满这种取巧的方法来当成文档用，但是刚好可以利用文档自身的多层嵌套功能来解决白板的层级问题。

第三点，感觉做成插件形式的话，白板跟文档之间割裂感会更强一点。挂件依托所在的文档，至少可以在全局搜索中通过文档名或者别名whiteboard来搜索到，在用`{{+关键词`的形式来搜索、插入嵌入块的时候同理。如果做成插件，我暂时没想到好的方法来融入思源自身的搜索中。

当然，目前这个挂件以嵌入块形式嵌入文档的时候还没处理好导出文档时的兼容性，所以如果是在文档中绘图，我更推荐集市中另外一款Excalidraw挂件。

**Comment by TinkMingKing** [comment]
感谢解答，另外，挂件不会隐藏块标，可否添加代码隐藏块标，并在白板中添加按钮以支持移除挂件
![image](https://github.com/user-attachments/assets/ab83c128-60bb-40aa-82c9-cdc2fb4a8ff1)

**Comment by BryceAndJuly** [comment]
隐藏块标的话用CSS片段就可以了

```css
/* 隐藏白板所在文档中内容块的块标 */
.protyle-content:has(.protyle-wysiwyg[alias="whiteboard"]) ~ .protyle-gutters {
    display: none !important;
}
```

移除挂件的话，我一般都是直接删除白板文档，因为是在空白文档中嵌入白板的，文档里也没其他东西。

如果不小心在有内容的文档里嵌入了该挂件，遮挡了其他内容，可以临时关闭一下这个代码片段，然后用挂件本身的块标来删除就好了。
