### ISSUE TITLE
能否优化查看模式和预览模式

### ISSUE THREAD

**Issue by ONIONLYONE** [BryceAndJuly/Whiteboard#31]
感谢大佬开发，请问能否设置默认开启预览模式和查看模式，每次打开文档都需要重新开启，比较麻烦。另外查看模式能否实现隐藏所有功能键（包括刷新，保存等等），这样比较纯粹，谢谢。

**Comment by BryceAndJuly** [comment]
那你改它的初始值好了，让它默认打开`查看模式`。

1、调整`viewModeEnabled`的初始值，默认开启查看模式。

打开`Whiteboard/assets/index-c894b550.js`，搜索：

```js
zoom:{value:1},viewModeEnabled:!1
```

改成：

```js
zoom:{value:1},viewModeEnabled:!0
```

2、`查看模式`下隐藏【保存】、【刷新】按钮

打开`Whiteboard/assets/index-8a263e3d.css`，在末尾加上以下两个样式并保存。

```css
/* 查看模式下，隐藏【保存】、【刷新】按钮 */
div#root:has( .excalidraw.excalidraw-container.excalidraw--view-mode) ~ #refreshBtn {
    display: none;
}
div#root:has( .excalidraw.excalidraw-container.excalidraw--view-mode) ~ #saveBtn{
    display: none;
}
```


> 备注：通过快捷键Alt+R来关闭`查看模式`时如果没生效，大概因为白板没获得焦点，可以鼠标点一下左下角的【重置缩放】后再按。或者直接鼠标右键菜单来关闭`查看模式`

**Comment by ONIONLYONE** [comment]
> 那你改它的初始值好了，让它默认打开`查看模式`。
> 
> 1、调整`viewModeEnabled`的初始值，默认开启查看模式。
> 
> 打开`Whiteboard/assets/index-c894b550.js`，搜索：
> 
> ```js
> zoom:{value:1},viewModeEnabled:!1
> ```
> 
> 改成：
> 
> ```js
> zoom:{value:1},viewModeEnabled:!0
> ```
> 
> 2、`查看模式`下隐藏【保存】、【刷新】按钮
> 
> 打开`Whiteboard/assets/index-8a263e3d.css`，在末尾加上以下两个样式并保存。
> 
> ```css
> /* 查看模式下，隐藏【保存】、【刷新】按钮 */
> div#root:has( .excalidraw.excalidraw-container.excalidraw--view-mode) ~ #refreshBtn {
>     display: none;
> }
> div#root:has( .excalidraw.excalidraw-container.excalidraw--view-mode) ~ #saveBtn{
>     display: none;
> }
> ```
> 
> > 备注：通过快捷键Alt+R来关闭`查看模式`时如果没生效，大概因为白板没获得焦点，可以鼠标点一下左下角的【重置缩放】后再按。或者直接鼠标右键菜单来关闭`查看模式`

大佬，我用记事本修改试了一下。
第一个改完之后内容显示空白了，只有左上角的【保存】和右上角的【刷新】还在，除此之外啥都没有，也不能通过右键或alt+R也无法退出查看模式。新建挂件也是空白＋【保存】【刷新】两个按钮。把代码改回来也没有变化，只能卸载挂件重装。
第二个测试了没有问题。但想请问下左上角的菜单按钮和坐下的缩放按钮也能隐藏吗？
谢谢。

**Comment by BryceAndJuly** [comment]
不应该啊，我试了可以才发给你的。你挂件版本是V1.3.2吗？第一个你用搜索和替换，别手动删，手动删容易把搜索的内容一起删了。

**Comment by BryceAndJuly** [comment]
查看模式下，隐藏左下、左上按钮的话，试试这个吧

```css
.excalidraw.excalidraw--view-mode .Stack_vertical {
    display: none;
}
```
