### ISSUE TITLE
文档左边的菜单按钮能否隐藏，，收起文档树时会跟左侧边栏的按钮显示叠在一起

### ISSUE THREAD

**Issue by entps** [BryceAndJuly/Whiteboard#6]
<img width="1506" alt="iShot_2024-01-04_15 57 26" src="https://github.com/BryceAndJuly/Whiteboard/assets/125341841/38c83041-a432-4d62-8f21-08a331b5eff2">

**Comment by BryceAndJuly** [comment]
这个块标的按钮是鼠标悬浮在内容块上时显示在左上角的，共用的，你如果通过CSS片段来将它隐藏掉，那文档里其他块，比如：文本、代码块、标题块、引述块哪些的块标也没了，你连块的操作入口都找不到，**不建议你这么做**。

```js
.protyle-gutters {
    display: none;
}
```

况且它并不影响文档树这边【新建子文档】的按钮的点击（默认主题下，依然能点击到），你折腾它干啥。

**Comment by BryceAndJuly** [comment]
之前回复的有些草率了，今天看到新Issue的时候才想起来，挂件会自动设置文档别名为whiteboard，利用这点可以单独隐藏挂件所在文档的块标而不影响其他文档。

```css
/* 隐藏白板所在文档中内容块的块标 */
.protyle-content:has(.protyle-wysiwyg[alias="whiteboard"]) ~ .protyle-gutters {
    display: none !important;
}
```
