### ISSUE TITLE
请问下，左上角的保存怎么关闭

### ISSUE THREAD

**Issue by su-dabiao** [BryceAndJuly/Whiteboard#62]
![Image](https://github.com/user-attachments/assets/42ccdf38-bc8d-4369-8ca4-c8cc6cb7cf1a)

我需要自动保存功能

但能否把这个提示关掉

Thanks♪(･ω･)ﾉ

**Comment by 753769554** [comment]
![Image](https://github.com/user-attachments/assets/508270a1-4a8b-4d3b-936d-4ec91769f124)

请问下，按照这个方式取消全屏了，我现在又想恢复插入后直接全屏

卸载重装啦，但还是取消全屏的状态


恢复全屏的代码是多少（下次一定先备份一份再操作）

**Comment by 753769554** [comment]
查看模式，是可以去掉的，

但能否永久去掉呢，省得每次都点击查看模式啦

Thanks  ♪(･ω･)ﾉ

**Comment by BryceAndJuly** [comment]
自带的温馨提示都不要啦？
好吧，那就隐藏掉吧。
```css
.excalidraw-app .HintViewer {
    display: none !important;
}
```
